# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 05:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PTT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('author_id', models.CharField(blank=True, default='', max_length=100)),
                ('nick_name', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateTimeField()),
                ('contents', models.TextField()),
                ('comments', django.contrib.postgres.fields.jsonb.JSONField()),
                ('url', models.CharField(blank=True, default='', max_length=300, unique=True)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
