# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 04:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTTRankServerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_comments', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
