# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTTRankServerApp', '0004_ptt_board'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ptt',
            options={'ordering': ('-date', 'id')},
        ),
        migrations.AddField(
            model_name='ptt',
            name='hot',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
